"""
prompts/ground_truth.py — Ground-truth SQL queries for the 50 benchmark questions.
Used to calculate Execution Accuracy (EA) during benchmark runs.
"""

GROUND_TRUTH_SQL = {
    "List all products": 'SELECT * FROM products;',
    "Get all customers": 'SELECT * FROM customers;',
    "Show all orders": 'SELECT * FROM orders;',
    "List all employees": 'SELECT * FROM employees;',
    "Get all offices": 'SELECT * FROM offices;',
    "Show all product lines": 'SELECT * FROM productlines;',
    "List all payments": 'SELECT * FROM payments;',
    "Get product names and prices": 'SELECT "productName", "buyPrice", "MSRP" FROM products;',
    "Get customer names and cities": 'SELECT "customerName", "city" FROM customers;',
    "List employee first and last names": 'SELECT "firstName", "lastName" FROM employees;',
    "Get all order dates": 'SELECT "orderNumber", "orderDate" FROM orders;',
    "Show product vendor list": 'SELECT DISTINCT "productVendor" FROM products;',
    "Get all product codes": 'SELECT "productCode" FROM products;',
    "List all countries from offices": 'SELECT DISTINCT "country" FROM offices;',
    "Show all order statuses": 'SELECT DISTINCT "status" FROM orders;',
    "Get all payment amounts": 'SELECT "customerNumber", "checkNumber", "amount" FROM payments;',
    "List all job titles": 'SELECT DISTINCT "jobTitle" FROM employees;',
    "Get customer phone numbers": 'SELECT "customerName", "phone" FROM customers;',
    "Show product MSRP values": 'SELECT "productName", "MSRP" FROM products;',
    "List order numbers": 'SELECT "orderNumber" FROM orders;',
    "Get orders with customer names": 'SELECT o."orderNumber", o."orderDate", o."status", c."customerName" FROM orders o JOIN customers c ON o."customerNumber" = c."customerNumber";',
    "Get employees with office city": 'SELECT e."firstName", e."lastName", e."jobTitle", o."city" FROM employees e JOIN offices o ON e."officeCode" = o."officeCode";',
    "Get payments with customer names": 'SELECT c."customerName", p."checkNumber", p."paymentDate", p."amount" FROM payments p JOIN customers c ON p."customerNumber" = c."customerNumber";',
    "Get order details with product names": 'SELECT od."orderNumber", p."productName", od."quantityOrdered", od."priceEach" FROM orderdetails od JOIN products p ON od."productCode" = p."productCode";',
    "Get products with product line description": 'SELECT p."productName", pl."productLine", pl."textDescription" FROM products p JOIN productlines pl ON p."productLine" = pl."productLine";',
    "Get customers with sales rep names": 'SELECT c."customerName", e."firstName" || \' \' || e."lastName" AS "salesRepName" FROM customers c JOIN employees e ON c."salesRepEmployeeNumber" = e."employeeNumber";',
    "Get orders with customer city": 'SELECT o."orderNumber", o."orderDate", c."customerName", c."city" FROM orders o JOIN customers c ON o."customerNumber" = c."customerNumber";',
    "Get employees and their manager": 'SELECT e1."firstName" || \' \' || e1."lastName" AS "employee", e2."firstName" || \' \' || e2."lastName" AS "manager" FROM employees e1 LEFT JOIN employees e2 ON e1."reportsTo" = e2."employeeNumber";',
    "Get orderdetails with product vendor": 'SELECT od."orderNumber", p."productName", p."productVendor", od."quantityOrdered" FROM orderdetails od JOIN products p ON od."productCode" = p."productCode";',
    "Get payments with customer country": 'SELECT c."customerName", c."country", p."amount", p."paymentDate" FROM payments p JOIN customers c ON p."customerNumber" = c."customerNumber";',
    "Count customers per country": 'SELECT "country", COUNT("customerNumber") AS "customerCount" FROM customers GROUP BY "country" ORDER BY "customerCount" DESC;',
    "Total payments per customer": 'SELECT c."customerName", SUM(p."amount") AS "totalPaid" FROM payments p JOIN customers c ON p."customerNumber" = c."customerNumber" GROUP BY c."customerName" ORDER BY "totalPaid" DESC;',
    "Number of orders per status": 'SELECT "status", COUNT("orderNumber") AS "orderCount" FROM orders GROUP BY "status" ORDER BY "orderCount" DESC;',
    "Products per product line": 'SELECT "productLine", COUNT("productCode") AS "productCount" FROM products GROUP BY "productLine" ORDER BY "productCount" DESC;',
    "Employees per office": 'SELECT o."city", COUNT(e."employeeNumber") AS "employeeCount" FROM employees e JOIN offices o ON e."officeCode" = o."officeCode" GROUP BY o."city" ORDER BY "employeeCount" DESC;',
    "Total stock per product vendor": 'SELECT "productVendor", SUM("quantityInStock") AS "totalStock" FROM products GROUP BY "productVendor" ORDER BY "totalStock" DESC;',
    "Average buy price per product line": 'SELECT "productLine", ROUND(AVG("buyPrice"), 2) AS "avgBuyPrice" FROM products GROUP BY "productLine" ORDER BY "avgBuyPrice" DESC;',
    "Orders per customer": 'SELECT c."customerName", COUNT(o."orderNumber") AS "orderCount" FROM orders o JOIN customers c ON o."customerNumber" = c."customerNumber" GROUP BY c."customerName" ORDER BY "orderCount" DESC;',
    "Max MSRP per product line": 'SELECT "productLine", MAX("MSRP") AS "maxMSRP" FROM products GROUP BY "productLine" ORDER BY "maxMSRP" DESC;',
    "Min buy price per vendor": 'SELECT "productVendor", MIN("buyPrice") AS "minBuyPrice" FROM products GROUP BY "productVendor" ORDER BY "minBuyPrice";',
    "Total number of customers": 'SELECT COUNT("customerNumber") AS "totalCustomers" FROM customers;',
    "Total number of products": 'SELECT COUNT("productCode") AS "totalProducts" FROM products;',
    "Total revenue from payments": 'SELECT SUM("amount") AS "totalRevenue" FROM payments;',
    "Average product price": 'SELECT ROUND(AVG("buyPrice"), 2) AS "avgBuyPrice" FROM products;',
    "Max payment amount": 'SELECT MAX("amount") AS "maxPayment" FROM payments;',
    "Min payment amount": 'SELECT MIN("amount") AS "minPayment" FROM payments;',
    "Count total orders": 'SELECT COUNT("orderNumber") AS "totalOrders" FROM orders;',
    "Total quantity in stock": 'SELECT SUM("quantityInStock") AS "totalStock" FROM products;',
    "Average MSRP": 'SELECT ROUND(AVG("MSRP"), 2) AS "avgMSRP" FROM products;',
    "Number of employees": 'SELECT COUNT("employeeNumber") AS "totalEmployees" FROM employees;'
}
